version: '3.3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    depends_on:
      - db
    volumes:
      - ./backend:/code
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    restart: on-failure
    environment:
      - DEBUG=1
      - SECRET_KEY="y&x(u-n@sz#z-n_)!%hz+p7+px%i6m3g%%(t1^7h*o=yfvem(i"
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_USER=template_user_prod
      - SQL_DATABASE=template_db_prod
      - SQL_PASSWORD=123456abc
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=template_user_prod
      - POSTGRES_DB=template_db_prod
      - POSTGRES_PASSWORD=123456abc

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - backend
    volumes:
      - ./backend/media/:/code/media/
      - ./backend/static/:/code/static/
      - ./nginx/prod.conf:/etc/nginx/nginx.conf:ro

volumes:
  postgres_data:
